### ISSUE TITLE
Remove quack library usage

### ISSUE THREAD

**Issue by kvark** [PistonDevelopers/hematite#215]
Impossible to get it compiling on latest as long as it's using quack.

**Comment by bvssvni** [comment]
quack is deprecated. All the methods are replaced with new design.

**Comment by mattico** [comment]
I'm working on this right now.  The new rust nightly broke a bunch of stuff which means that there's dependency hell with all of the piston and gfx-rs stuff, but I almost have it finished.

**Comment by kvark** [comment]
@mattico nice! If you succeed, we may even be able to make Hematite running on rust beta/release in time.

**Comment by mattico** [comment]
@kvark I'm targetting the current nightly at the moment because that's what I have, but once I finish I'll see what work (if any) it'll take to target beta. 

For a bit of a progress report:
* `cargo update`
* `flate` (deprecated) -> `flate2`
* `os::MemoryMap` -> `mmap`
* `rustc-serialize` `0.2.8` -> `0.3.x`
* `range(a, b)` -> `a..b`
* `old_io` -> `io`

and other misc. changes to remove deprecated stuff.

Currently having some issues figuring out the last 18 errors, which are related to some changes in gfx-rs.

**Comment by kvark** [comment]
@mattico I'd be happy to assist with any gfx-related questions What errors do you get?

**Comment by mattico** [comment]
@kvark The current version is here: https://github.com/mattico/hematite/tree/remove-quack

The `Renderer` struct in `src/shader.rs` needs changing so that the graphics field matches the new types from gfx-rs, and I've probably done it wrong since I haven't really looked too deeply into gfx-rs.

There's also a bunch of method/trait not implemented errors in `main.rs`, even though the methods _are_ implemented from what I see. There must be some type that changed somewhere and now the impls aren't in scope.

**Comment by mattico** [comment]
@kvark I completely forgot that I removed quack already, that explains a lot of the strange type errors.

**Comment by kvark** [comment]
@mattico a good practice would be to file a PR in progress (add `[WIP]` to the title or something). This way I'd be able to point to specific places in code and suggest fixes, or even take your stuff and fix all gfx error, submitting a new PR from it.

**Comment by mattico** [comment]
@kvark Yep, I was going to do that earlier but I got busy.  I'll do that now.
