### ISSUE TITLE
Base code systems on this Minecraft C# clean-room reimplementation

### ISSUE THREAD

**Issue by hardBSDk** [PistonDevelopers/hematite#313]
This Minecraft 1.7.3 clean-room implementation is very complete, you can base your code on it.

https://github.com/ddevault/TrueCraft

(Despite being written in C#, it did a lot of reverse-enginnering of Minecraft beta, it's important for documentation of the Minecraft systems).

**Comment by eddyb** [comment]
The plan, back in the day, was to rely on the data model changes in 1.13 (aka "the flattening") which a bunch of people already knew was coming from 2013-2014 (via personal discussions with Mojang developers).

That never happened because it took them too long (1.13 came out in 2017 IIRC), and I was too busy with other things by then, but it's been tempting to pick it back up.

Anyway, 1.7.x would be going backwards.
